# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastapi-nbdev',
                'doc_host': 'https://MeesMolenaar.github.io',
                'git_url': 'https://github.com/MeesMolenaar/fastapi-nbdev',
                'lib_path': 'fastapi_nbdev'},
  'syms': {'fastapi_nbdev.core': {'fastapi_nbdev.core.foo': ('core.html#foo', 'fastapi_nbdev/core.py')}}}
