# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['app', 'root']

# %% ../nbs/00_main.ipynb 3
from fastapi import FastAPI
from .routers import aroute

# %% ../nbs/00_main.ipynb 4
app = FastAPI()

# %% ../nbs/00_main.ipynb 5
app.include_router(aroute.router)

# %% ../nbs/00_main.ipynb 6
@app.get("/")
async def root():
    return {"message": "Hello World"}
