# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routers/00_aroute.ipynb.

# %% auto 0
__all__ = ['router', 'artoue']

# %% ../../nbs/routers/00_aroute.ipynb 3
from fastapi import APIRouter

# %% ../../nbs/routers/00_aroute.ipynb 4
router = APIRouter()

# %% ../../nbs/routers/00_aroute.ipynb 5
@router.get('/aroute')
async def artoue():
    return {"message": "Welcome in aroute!"}
